# 基础镜像
FROM openjdk:11.0-jre-buster
# 设定时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 拷贝jar包
COPY trade-service.jar /trade-service.jar
# 入口
ENTRYPOINT ["java", "-jar", "/trade-service.jar"]